spring.application.name=PathIO

spring.datasource.url=
spring.datasource.username=pathio
spring.datasource.password=postgres
spring.jpa.hibernate.ddl.auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

